create table member_info_hist (
mem_num bigint not null,
update_date datetime,
mem_id varchar(20) not null,
nick_name varchar(32),
mem_pwd varchar(32) not null,
mem_kind_cd varchar(1),
mem_atbt_cd varchar(1) not null,
question_cd int not null,
answer varchar(32) not null,
mail_pc varchar(100) not null,
mail_mobile varchar(10),
kanji_fname varchar(10),
kanji_lname varchar(10),
kana_fname varchar(10),
kana_lname varchar(10),
sex_cd int,
birth_ymd datetime,
divis_cd int,
occup_cd int,
city_name varchar(50),
building_name varchar(50),
tel_num varchar(20),
mailmag_req_cd varchar(1),
mailmag_obj_cd varchar(1),
note varchar(255),
entry_ip varchar(15),
entry_date datetime,
login_ip varchar(15),
login_date datetime,
login_fail_ip varchar(15),
login_fail_date datetime,
login_fail_cnt int,
last_update_ip varchar(15),
last_update_date datetime,
version_no int,
primary key (mem_num, update_date)
)
