create table member_infn (
mem_num bigint not null auto_increment,
mem_id nvarchar(20) not null,
mem_name nvarchar(32),
mem_pwd nvarchar(32) not null,
mem_kind_cd nvarchar(1),
mem_atbt_cd nvarchar(1) not null,
question_cd int not null,
answer nvarchar(32) not null,
mail_pc nvarchar(100) not null,
mail_mobile nvarchar(100),
sex_cd int,
birth_ymd datetime,
divis_cd int,
occup_cd int,
area nvarchar(100),
tel_num nvarchar(20),
mailmag_req_cd nvarchar(1),
mailmag_obj_cd nvarchar(1),
note nvarchar(255),
entry_ip nvarchar(15),
entry_ymd datetime,
login_ymd_ip nvarchar(15),
login_ymd datetime,
login_fail_ip nvarchar(15),
login_fail_ymd datetime,
login_fail_cnt int,
update_ip nvarchar(15),
update_ymd datetime,
version_no int,
primary key (mem_num)
)
