create table inquiry_info (
inquiry_num bigint not null auto_increment,
inquiry_date datetime,
mem_id varchar(20),
company_name varchar(40),
company_meidia_name varchar(40),
company_user_name varchar(20),
user_name varchar(20),
user_mailadd varchar(100),
tel_num varchar(10),
title_id int,
inquiry_type int,
inquiry_kind_code int,
inquiry_object varchar(240),
inquiry_contents text,
response_date datetime,
response_subject varchar(240),
response_contents text,
from_subject varchar(40),
from_mailadd varchar(100),
reply_to varchar(100),
correspond_status int,
correspond_user_id varchar(20),
correspond_user_name varchar(20),
created_date datetime,
created_user varchar(50),
last_update_date datetime,
last_update_user varchar(50),
primary key (inquiry_num)
)
